name: Kali Linux Remote Desktop

on:
  workflow_dispatch:

jobs:
  kali-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Start Kali RDP Server
        run: |
          docker run -d --name kali -p 3389:3389 --expose 3389 lscr.io/linuxserver/kali-linux:latest
          sudo apt update && sudo apt install -y net-tools

      - name: Install & Run Bore Tunnel
        run: |
          wget https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          tar -xf bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          ./bore local 3389 --to bore.pub

      - name: Keep Alive
        run: sleep 21600
        
