name: Kali Linux Remote Desktop

on:
  workflow_dispatch:

jobs:
  kali-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop & XRDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp dbus-x11
          
          # Setup Desktop Session for RDP
          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:Pass1234" | sudo chpasswd
          sudo usermod -aG sudo rdpuser
          
          # Fix Session Error
          echo "startxfce4" | sudo tee /home/rdpuser/.xsession
          sudo chown rdpuser:rdpuser /home/rdpuser/.xsession
          
          # Configure XRDP Startup Script
          sudo sed -i.bak '/test -x \/etc\/X11\/Xsession/i export XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share:/usr/share\nexport XDG_CONFIG_DIRS=/etc/xdg\nstartxfce4 &' /etc/xrdp/startwm.sh
          
          sudo systemctl restart xrdp

      - name: Install Kali Core Tools
        run: |
          sudo apt install -y nmap htop curl wget git

      - name: Install & Run Bore Tunnel
        run: |
          wget https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          tar -xf bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          ./bore local 3389 --to bore.pub

      - name: Keep Alive
        run: sleep 21600
        
