name: Cardless Windows RDP

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create User & Enable RDP
        run: |
          net user rdpuser Pass1234 /add
          net localgroup administrators rdpuser /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

      - name: Start Pinggy TCP Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -p 443 -R 0:localhost:3389 a.pinggy.io

      - name: Keep Alive
        run: Start-Sleep -Seconds 21600
